//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidateErrorMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateErrorMessagesResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Shared.Resources.ValidateErrorMessagesResource", typeof(ValidateErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的长度必须恰好是{1} 的本地化字符串。
        /// </summary>
        public static string ArrayLenValidationError {
            get {
                return ResourceManager.GetString("ArrayLenValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的长度不能大于{1} 的本地化字符串。
        /// </summary>
        public static string ArrayMaxValidationError {
            get {
                return ResourceManager.GetString("ArrayMaxValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的长度不能小于{1} 的本地化字符串。
        /// </summary>
        public static string ArrayMinValidationError {
            get {
                return ResourceManager.GetString("ArrayMinValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的长度必须介于{1}和{2}之间 的本地化字符串。
        /// </summary>
        public static string ArrayRangeValidationError {
            get {
                return ResourceManager.GetString("ArrayRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}和{1}不匹配。 的本地化字符串。
        /// </summary>
        public static string CompareMustMatchValidationError {
            get {
                return ResourceManager.GetString("CompareMustMatchValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段{0}上的验证错误 的本地化字符串。
        /// </summary>
        public static string DefaultValidationError {
            get {
                return ResourceManager.GetString("DefaultValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}字段不是有效的电子邮件地址 的本地化字符串。
        /// </summary>
        public static string EmailAddressValidationError {
            get {
                return ResourceManager.GetString("EmailAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须等于{1} 的本地化字符串。
        /// </summary>
        public static string NumberLenValidationError {
            get {
                return ResourceManager.GetString("NumberLenValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能大于{1} 的本地化字符串。
        /// </summary>
        public static string NumberMaxValidationError {
            get {
                return ResourceManager.GetString("NumberMaxValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能小于{1} 的本地化字符串。
        /// </summary>
        public static string NumberMinValidationError {
            get {
                return ResourceManager.GetString("NumberMinValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须介于{1}和{2}之间 的本地化字符串。
        /// </summary>
        public static string NumberRangeValidationError {
            get {
                return ResourceManager.GetString("NumberRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须是[{1}]中的一个 的本地化字符串。
        /// </summary>
        public static string OneOfValidationError {
            get {
                return ResourceManager.GetString("OneOfValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}与模式{1}不匹配 的本地化字符串。
        /// </summary>
        public static string PatternMismatchValidationError {
            get {
                return ResourceManager.GetString("PatternMismatchValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}字段是必需的 的本地化字符串。
        /// </summary>
        public static string RequiredValidationError {
            get {
                return ResourceManager.GetString("RequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须恰好是{1}个字符 的本地化字符串。
        /// </summary>
        public static string StringLenValidationError {
            get {
                return ResourceManager.GetString("StringLenValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能超过{1}个字符 的本地化字符串。
        /// </summary>
        public static string StringMaxValidationError {
            get {
                return ResourceManager.GetString("StringMaxValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须至少为{1}个字符 的本地化字符串。
        /// </summary>
        public static string StringMinValidationError {
            get {
                return ResourceManager.GetString("StringMinValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}字符数必须介于{1}和{2}之间 的本地化字符串。
        /// </summary>
        public static string StringRangeValidationError {
            get {
                return ResourceManager.GetString("StringRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不是有效的{1} 的本地化字符串。
        /// </summary>
        public static string TypesDefaultValidationError {
            get {
                return ResourceManager.GetString("TypesDefaultValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已存在 的本地化字符串。
        /// </summary>
        public static string UniqueValueValidationError {
            get {
                return ResourceManager.GetString("UniqueValueValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空 的本地化字符串。
        /// </summary>
        public static string WhitespaceValidationError {
            get {
                return ResourceManager.GetString("WhitespaceValidationError", resourceCulture);
            }
        }
    }
}
